### ISSUE TITLE
Last version cause the CI builds to get stuck forever (Azure + CircleCi)

### ISSUE THREAD

**Issue by mamcx** [clux/muslrust#84] opened 2021-09-09 17:09 UTC
As I put on https://www.reddit.com/r/rust/comments/pkifk2/my_rust_ci_builds_get_stuck_forever_up_to_50_min/, my CI builds get stuck forever and the CI platform kill them.

Then I put an old version (muslrust:1.56.0-nightly-2021-08-19) and now it work fine again.

P.D: I always pull muslrust without any tag before.

**Comment by clux** [comment] 2021-09-09 20:00
A fun part about this issue is that since you built with `:latest` I'm not sure if it's today's nightly or today's stable you tried.
I would recommend at least pinning to the channel you want (`:stable` or `:nightly`) rather than nothing (`:latest`, whatever's built last).

But that's still a strange build error. Tried forcing a build on `controller-rs` and it compiles fine with the last `:stable` image:  see the [circle build log](https://app.circleci.com/pipelines/github/kube-rs/controller-rs/113/workflows/45407503-53f0-418b-9151-e3c4e02bbcff/jobs/190). It uses actix, but maybe your app is bigger though.

Going to guess this is a `nightly` issue as sometimes nightly is weird, but then i don't use more than a handful of nightly releases so can't really tell.

At any rate, I can't really reproduce it. It looks like my `nightly` build is going through as well, but nightly has a [compile issue with that app anyway](https://app.circleci.com/pipelines/github/kube-rs/controller-rs/112/workflows/627452f0-fe3e-48b7-b9b7-ea0cb79029f0/jobs/189) so can't get it to 100%, but not sure that that matters.

If it's a nightly regression, then presumably someone else will join in on this issue. I'll leave this open for a week or two, and see if that's the case.

**Comment by mamcx** [comment] 2021-09-09 20:39
Yeah, I will pin version moving forward (this is the second time I break builds because I don't). The workaround is enough for me but I report it anyway in case somebody else get hit and at least get some clue.

**Comment by clux** [comment] 2021-10-02 14:28
Going to close this as no one else has reported anything similar in the past 3 weeks.

**Closed by clux** 2021-10-02 14:28 UTC
