### ISSUE TITLE
Build and fetch errors with clux/muslrust:1.60.0

### ISSUE THREAD

**Issue by Nutomic** [clux/muslrust#94] opened 2022-05-16 11:48 UTC
We are suddenly getting some weird failures in our build using clux/muslrust:1.60.0 on cloud.drone.io. First one is this:
```
+ git fetch --tags

fatal: unable to access 'https://github.com/LemmyNet/lemmy.git/': getaddrinfo() thread failed to start
```

And second, this:
```
+ cargo check -p lemmy_api_common
error: could not execute process `rustc -vV` (never executed)

Caused by:
  Operation not permitted (os error 1)
```

A few days ago the same ci build worked fine, was the image updated to a broken one in the meantime? For now i downgraded to muslrust:1.59.0 and it works fine.

**Comment by clux** [comment] 2022-05-16 12:43
Ohh. That might be related to the os upgrade yeah. Didn't test that git worked. I'll have a quick look later.

**Comment by charlesndalton** [comment] 2022-05-16 23:05
Also randomly getting "error: could not execute process `rustc -vV` (never executed)"

**Comment by Nutomic** [comment] 2022-05-20 10:50
FYI it seems the error with `getaddrinfo() thread failed to start` only happens when running in [drone.io](https://www.drone.io/) (and happens every time). But local builds work fine.

**Comment by clux** [comment] 2022-05-20 10:52
Ah, thanks a lot for this update. I was struggling to reproduce anything myself.

If anyone still has issues with the new jammy version it would be helpful to have a Dockerfile and a link to a how it's built (e.g. github action invocations).

**Comment by Nutomic** [comment] 2022-05-20 11:07
We are using this config for drone.io: https://github.com/LemmyNet/lemmy/blob/main/.drone.yml

You should be able to reproduce by copying it into a new project (or forking), and changing the Docker image version. Then enable [cloud.drone.io](https://cloud.drone.io) CI for the repo.  The error already happens in the first step at `git fetch --tags` ([example output](https://cloud.drone.io/LemmyNet/lemmy/3383/1/3)). 

I can also test things if you tell me how to get useful info out of it.

**Comment by clux** [comment] 2022-05-24 19:19
@xD3CODER : you also on drone.io?

not able to do a full test against drone myself since they are no longer accepting new registrations, but can see if i can reproduce via a test case on github actions by emulating what lemmy is doing in gha.

**Comment by xD3CODER** [comment] 2022-05-24 19:33
> @xD3CODER : you also on drone.io?
> 
> not able to do a full test against drone myself since they are no longer accepting new registrations, but can see if i can reproduce via a test case on github actions by emulating what lemmy is doing in gha.

For me it happens on local Docker build

**Comment by clux** [comment] 2022-05-24 19:37
@xD3CODER : oh can actually be very helpful. Do you have something public (or a Dockerfile) and what command that is failing (if it's not a git fetch error).

**Comment by clux** [comment] 2022-05-24 20:06
Ultimately tests manage to run git fetch fine, both locally and in CI (#100). Possibly this is permission related. The users and groups haven't changed, but maybe caches from a previous container is interacting badly :thinking: maybe cargo clean first? (saw a similar error via https://github.com/rust-lang/cargo/issues/2305)

For the `git` error, I'm not sure what's exactly is happening there. `git` was upgraded. Maybe [something to do with the git config](https://stackoverflow.com/questions/59911649/fatal-unable-to-access-link-getaddrinfo-thread-failed-to-start)? People are seeing [the same git error](https://docs.microsoft.com/en-us/answers/questions/293076/trouble-with-cloning-github-repo-on-azure-commandl.html) in different CI systems. [This post](https://openforums.blog/2021/12/15/tracing-curl-error-6-getaddrinfo-thread-failed-to-start-error-with-systemd-seccomp-filters/) suggests setting `export SYSTEMD_SECCOMP=0`.

**Comment by xD3CODER** [comment] 2022-05-25 10:29
@clux The following Dockerfile fails at `cargo build` with 
```
error: could not execute process `rustc -vV` (never executed)

Caused by:
  Operation not permitted (os error 1)

```

```
FROM clux/muslrust:latest as builder
WORKDIR /app
RUN cargo new --bin api
WORKDIR /app/api
RUN cargo build --release
```

**Comment by clux** [comment] 2022-05-25 13:18
Thanks both. I have added this trivial dockerfile as a test case in #100 although it is passing both on github actions and locally. This is almost certainly a security restriction somewhere.

Can't look more until tonight, but any info about setups (`id` (showing group membership), os setup (selinux / distro)) is helpful in the meantime. Will try the drone setup tonight/tomorrow.

**Comment by Nutomic** [comment] 2022-05-27 11:19
Its strange, [drone.yerbamate.ml seems to have fixed itself](https://drone.yerbamate.ml/LemmyNet/lemmy/1136/1/5). Dont think i  changed anything there except install system updates and reboot. But the same error is [still happening on cloud.drone.io](https://cloud.drone.io/LemmyNet/lemmy/3541/1/3).

I opened a thread about this in the [Drone Support forum](https://community.harness.io/t/build-fails-with-getaddrinfo-thread-failed-to-start/12092).

**Comment by jrd-rocks** [comment] 2022-06-03 12:16
@[xD3CODER](https://github.com/xD3CODER) I had the same problem, after searching a bit (apt-get upgrade also failed, eg https://askubuntu.com/questions/1408528/apt-update-on-ubuntu22-04-results-in-error-100-on-some-docker-hosts) i found that docker apparently was bugged. I upgraded docker 2.10.7 to 2.10.12 (was docker-ce, i installed docker.io which is in the ubuntu repo) and the problem went away.

**Comment by xD3CODER** [comment] 2022-06-08 12:32
Thank's for your help @jrd-rocks .
I think my problem is due to the fact that I updated my Ubuntu distribution (focal -> jammy) without upgrading Docker

**Comment by clux** [comment] 2022-06-25 16:15
Given the updates on this, going to close this issue. Seems like the new ubuntu incidentally stumbled upon something weird, that's not really our fault.

**Closed by clux** 2022-06-25 16:15 UTC
Labels: help wanted
